# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcmean <- function(x, margin) {
    .Call('mixR_rcmean', PACKAGE = 'mixR', x, margin)
}

rcsum <- function(x, margin) {
    .Call('mixR_rcsum', PACKAGE = 'mixR', x, margin)
}

expZ_norm_C <- function(x, pi, mu, sd) {
    .Call('mixR_expZ_norm_C', PACKAGE = 'mixR', x, pi, mu, sd)
}

loglik_norm_C <- function(x, pi, mu, sd) {
    .Call('mixR_loglik_norm_C', PACKAGE = 'mixR', x, pi, mu, sd)
}

norm_uv <- function(x, pi, mu, sd, max_iter = 500L, tol = 1e-6) {
    .Call('mixR_norm_uv', PACKAGE = 'mixR', x, pi, mu, sd, max_iter, tol)
}

norm_ev <- function(x, pi, mu, sd, max_iter = 500L, tol = 1e-6) {
    .Call('mixR_norm_ev', PACKAGE = 'mixR', x, pi, mu, sd, max_iter, tol)
}

enorm_trunc <- function(a, b, mu = 0, sd = 1) {
    .Call('mixR_enorm_trunc', PACKAGE = 'mixR', a, b, mu, sd)
}

exnorm <- function(data, mu, sd) {
    .Call('mixR_exnorm', PACKAGE = 'mixR', data, mu, sd)
}

txnorm <- function(pi, mu, sd, ex) {
    .Call('mixR_txnorm', PACKAGE = 'mixR', pi, mu, sd, ex)
}

loglik_norm_gC <- function(data, pi, mu, sd) {
    .Call('mixR_loglik_norm_gC', PACKAGE = 'mixR', data, pi, mu, sd)
}

norm_uv_g <- function(data, pi, mu, sd, max_iter = 100L, tol = 1e-4) {
    .Call('mixR_norm_uv_g', PACKAGE = 'mixR', data, pi, mu, sd, max_iter, tol)
}

norm_ev_g <- function(data, pi, mu, sd, max_iter = 1000L, tol = 1e-4) {
    .Call('mixR_norm_ev_g', PACKAGE = 'mixR', data, pi, mu, sd, max_iter, tol)
}

expZ_gamma_C <- function(x, pi, alpha, lambda) {
    .Call('mixR_expZ_gamma_C', PACKAGE = 'mixR', x, pi, alpha, lambda)
}

loglik_gamma_C <- function(x, pi, alpha, lambda) {
    .Call('mixR_loglik_gamma_C', PACKAGE = 'mixR', x, pi, alpha, lambda)
}

gamma_bisection_C <- function(n, ex, tx, tol = 1e-4, max_iter = 100L, xleft = 0.1, xright = 5) {
    .Call('mixR_gamma_bisection_C', PACKAGE = 'mixR', n, ex, tx, tol, max_iter, xleft, xright)
}

to_mu_sd_gamma_C <- function(alpha, lambda) {
    .Call('mixR_to_mu_sd_gamma_C', PACKAGE = 'mixR', alpha, lambda)
}

to_alpha_lambda_gamma_C <- function(mu, sd) {
    .Call('mixR_to_alpha_lambda_gamma_C', PACKAGE = 'mixR', mu, sd)
}

gamma_C <- function(x, pi, alpha, lambda, method = "Newton", max_iter = 500L, tol = 1e-6) {
    .Call('mixR_gamma_C', PACKAGE = 'mixR', x, pi, alpha, lambda, method, max_iter, tol)
}

egamma_trunc <- function(a, b, alpha, lambda) {
    .Call('mixR_egamma_trunc', PACKAGE = 'mixR', a, b, alpha, lambda)
}

EXgamma_C <- function(data, alpha, lambda) {
    .Call('mixR_EXgamma_C', PACKAGE = 'mixR', data, alpha, lambda)
}

TXgamma_C <- function(pi, alpha, lambda, ex) {
    .Call('mixR_TXgamma_C', PACKAGE = 'mixR', pi, alpha, lambda, ex)
}

loglik_gamma_g_C <- function(data, pi, alpha, lambda) {
    .Call('mixR_loglik_gamma_g_C', PACKAGE = 'mixR', data, pi, alpha, lambda)
}

gamma_g_C <- function(data, pi, alpha, lambda, method = "Newton", max_iter = 500L, tol = 1e-6) {
    .Call('mixR_gamma_g_C', PACKAGE = 'mixR', data, pi, alpha, lambda, method, max_iter, tol)
}

expZ_weib_C <- function(x, pi, k, lambda) {
    .Call('mixR_expZ_weib_C', PACKAGE = 'mixR', x, pi, k, lambda)
}

loglik_weib_C <- function(x, pi, k, lambda) {
    .Call('mixR_loglik_weib_C', PACKAGE = 'mixR', x, pi, k, lambda)
}

g_weib <- function(r, n, ex, tx) {
    .Call('mixR_g_weib', PACKAGE = 'mixR', r, n, ex, tx)
}

newton_weib_C <- function(n, ex, tx, r = 1, max_iter = 100L) {
    .Call('mixR_newton_weib_C', PACKAGE = 'mixR', n, ex, tx, r, max_iter)
}

weib_bisection_C <- function(n, ex, tx, tol = 1e-4, max_iter = 100L, xleft = 0.1, xright = 5) {
    .Call('mixR_weib_bisection_C', PACKAGE = 'mixR', n, ex, tx, tol, max_iter, xleft, xright)
}

to_mu_sd_weib_C <- function(k, lambda) {
    .Call('mixR_to_mu_sd_weib_C', PACKAGE = 'mixR', k, lambda)
}

to_k_lambda_weib_C <- function(mu, sd) {
    .Call('mixR_to_k_lambda_weib_C', PACKAGE = 'mixR', mu, sd)
}

weib_C <- function(x, pi, k, lambda, method = "Newton", max_iter = 500L, tol = 1e-6) {
    .Call('mixR_weib_C', PACKAGE = 'mixR', x, pi, k, lambda, method, max_iter, tol)
}

eweib_trunc <- function(a, b, k, lambda) {
    .Call('mixR_eweib_trunc', PACKAGE = 'mixR', a, b, k, lambda)
}

EXweib_C <- function(data, k, lambda) {
    .Call('mixR_EXweib_C', PACKAGE = 'mixR', data, k, lambda)
}

TXweib_C <- function(pi, k, lambda, ex) {
    .Call('mixR_TXweib_C', PACKAGE = 'mixR', pi, k, lambda, ex)
}

loglik_weib_g_C <- function(data, pi, k, lambda) {
    .Call('mixR_loglik_weib_g_C', PACKAGE = 'mixR', data, pi, k, lambda)
}

weib_g_C <- function(data, pi, k, lambda, method = "Newton", max_iter = 500L, tol = 1e-6) {
    .Call('mixR_weib_g_C', PACKAGE = 'mixR', data, pi, k, lambda, method, max_iter, tol)
}

expZ_lnorm_C <- function(x, pi, mulog, sdlog) {
    .Call('mixR_expZ_lnorm_C', PACKAGE = 'mixR', x, pi, mulog, sdlog)
}

loglik_lnorm_C <- function(x, pi, mulog, sdlog) {
    .Call('mixR_loglik_lnorm_C', PACKAGE = 'mixR', x, pi, mulog, sdlog)
}

lnorm_C <- function(x, pi, mulog, sdlog, max_iter = 500L, tol = 1e-6) {
    .Call('mixR_lnorm_C', PACKAGE = 'mixR', x, pi, mulog, sdlog, max_iter, tol)
}

elnorm_trunc <- function(a, b, mulog, sdlog) {
    .Call('mixR_elnorm_trunc', PACKAGE = 'mixR', a, b, mulog, sdlog)
}

EXlnorm_C <- function(data, mulog, sdlog) {
    .Call('mixR_EXlnorm_C', PACKAGE = 'mixR', data, mulog, sdlog)
}

TXlnorm_C <- function(pi, mulog, sdlog, ex) {
    .Call('mixR_TXlnorm_C', PACKAGE = 'mixR', pi, mulog, sdlog, ex)
}

loglik_lnorm_g_C <- function(data, pi, mulog, sdlog) {
    .Call('mixR_loglik_lnorm_g_C', PACKAGE = 'mixR', data, pi, mulog, sdlog)
}

lnorm_g_C <- function(data, pi, mulog, sdlog, max_iter = 500L, tol = 1e-6) {
    .Call('mixR_lnorm_g_C', PACKAGE = 'mixR', data, pi, mulog, sdlog, max_iter, tol)
}

